# This is a workflow to download dependency charts from JFrog Artifactory and store them in the 'charts' directory of the repository.

name: Download Charts from JFrog Artifactory

on: 
  workflow_dispatch:
   inputs:
    VERSION:
      description: 'Version of the charts to download (e.g., 0.1.0)'
      default: '0.1.0'
      required: true
      type: string

jobs:
  download-charts:
    runs-on: self-hosted
    steps:
      - name: Download charts from JFrog
        run: |
          VERSION=${{ github.event.inputs.version }}
          mkdir -p microservices-platform/charts
          cd microservices-platform/charts
          
          for chart in auth-api frontend users-api todos-api redis-queue zipkin
          do
            echo "Downloading $chart version $VERSION"
            curl -f -u "${{ secrets.ARTIFACTORY_USER_NAME }}:${{ secrets.ARTIFACTORY_PASSWORD }}" -O ${{ secrets.ARTIFACTORY_URL }}/helm-charts/${chart}-${VERSION}.tgz
          done

        
      - name: List downloaded charts
        run: |
          echo "Downloaded charts:"
          ls -l microservices-platform/charts